services:
  # Backend Service
  - type: web
    name: quick-chat-backend
    env: node
    repo: https://github.com/your-username/quick-chat-backend.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: CLIENT_URL
        value: https://quick-chat-frontend.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Set this in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # Set this in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # Set this in Render dashboard

  # Frontend Service
  - type: web
    name: quick-chat-frontend
    env: static
    repo: https://github.com/your-username/quick-chat-frontend.git
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    envVars:
      - key: VITE_BACKEND_URL
        value: https://quick-chat-backend.onrender.com